version: '3.7'

services:
  postgres:
    container_name: postgres
    build:
      context: ./postgres
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: '/data/postgres'
      POSTGRES_DB: 'postgres'
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  postgres:


